package com.dasigconnect.backend.service;

import com.dasigconnect.backend.external.ClaudeVisionClient;
import com.dasigconnect.backend.external.VoyageAIClient;
import com.dasigconnect.backend.model.entity.MediaAssetEmbeddingType;
import com.dasigconnect.backend.repository.MediaAssetEmbeddingRepository;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

/** Generates the visual embedding stage without running media classification. */
@Service
public class MediaImageEmbeddingService {

    private static final Logger log = LoggerFactory.getLogger(MediaImageEmbeddingService.class);

    private final MediaAssetEmbeddingRepository embeddingRepository;
    private final ClaudeVisionClient imagePreparation;
    private final VoyageAIClient voyageAIClient;

    public MediaImageEmbeddingService(
            MediaAssetEmbeddingRepository embeddingRepository,
            ClaudeVisionClient imagePreparation,
            VoyageAIClient voyageAIClient) {
        this.embeddingRepository = embeddingRepository;
        this.imagePreparation = imagePreparation;
        this.voyageAIClient = voyageAIClient;
    }

    /**
     * Reuses a visual embedding generated by the current model, or creates it
     * from the stored image. This method does not classify the image, create a
     * semantic embedding, or change the media asset status.
     */
    public boolean generateOrReuse(UUID assetId, String storageUrl) {
        String model = voyageAIClient.multimodalModelName();
        if (embeddingRepository.existsCurrentEmbedding(
                assetId, MediaAssetEmbeddingType.IMAGE, model)) {
            return true;
        }

        ClaudeVisionClient.PreparedImage image;
        try {
            image = imagePreparation.prepareImageForEmbedding(storageUrl);
        } catch (Exception error) {
            log.warn("Failed to fetch image for multimodal embedding for asset {}: {}",
                    assetId, error.getMessage());
            return false;
        }

        String embeddingJson;
        try {
            embeddingJson = voyageAIClient.embedImageDocument(image.bytes(), image.mediaType());
        } catch (Exception error) {
            log.warn("Voyage AI image embedding failed for asset {}: {}", assetId, error.getMessage());
            return false;
        }

        try {
            embeddingRepository.upsert(
                    assetId,
                    MediaAssetEmbeddingType.IMAGE,
                    embeddingJson,
                    model);
            return true;
        } catch (Exception error) {
            log.warn("Failed to store image embedding for asset {}: {}", assetId, error.getMessage());
            return false;
        }
    }
}
