package com.dasigconnect.backend.service;

import com.dasigconnect.backend.external.ClaudeVisionClient;
import com.dasigconnect.backend.external.VoyageAIClient;
import com.dasigconnect.backend.model.entity.MediaAssetEmbeddingType;
import com.dasigconnect.backend.repository.MediaAssetEmbeddingRepository;
import java.util.UUID;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.HexFormat;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

/** Generates the visual embedding stage without running media classification. */
@Service
public class MediaImageEmbeddingService {

    private static final Logger log = LoggerFactory.getLogger(MediaImageEmbeddingService.class);

    private final MediaAssetEmbeddingRepository embeddingRepository;
    private final ClaudeVisionClient imagePreparation;
    private final VoyageAIClient voyageAIClient;

    @org.springframework.beans.factory.annotation.Autowired(required = false)
    private MediaAiTelemetryService mediaAiTelemetry;

    public MediaImageEmbeddingService(
            MediaAssetEmbeddingRepository embeddingRepository,
            ClaudeVisionClient imagePreparation,
            VoyageAIClient voyageAIClient) {
        this.embeddingRepository = embeddingRepository;
        this.imagePreparation = imagePreparation;
        this.voyageAIClient = voyageAIClient;
    }

    /**
     * Reuses a visual embedding generated by the current model, or creates it
     * from the stored image. This method does not classify the image, create a
     * semantic embedding, or change the media asset status.
     */
    public boolean generateOrReuse(UUID assetId, String storageUrl) {
        long startedAt = System.nanoTime();
        String model = voyageAIClient.multimodalModelName();
        String sourceHash = sha256(storageUrl == null ? "" : storageUrl.trim());
        String processingVersion = MediaProcessingQueueService.IMAGE_EMBEDDING_VERSION;
        if (embeddingRepository.existsCurrentVersionedEmbedding(
                assetId, MediaAssetEmbeddingType.IMAGE.dbValue(), model,
                sourceHash, 0L, processingVersion)) {
            record(assetId, startedAt, "REUSED", 0, 1);
            return true;
        }

        ClaudeVisionClient.PreparedImage image;
        try {
            image = imagePreparation.prepareImageForVisualEmbedding(storageUrl);
        } catch (Exception error) {
            log.warn("Failed to fetch image for multimodal embedding for asset {}: {}",
                    assetId, error.getMessage());
            record(assetId, startedAt, "FAILURE", 0, 0);
            return false;
        }

        String embeddingJson;
        try {
            embeddingJson = voyageAIClient.embedImageDocument(image.bytes(), image.mediaType());
        } catch (Exception error) {
            log.warn("Voyage AI image embedding failed for asset {}: {}", assetId, error.getMessage());
            record(assetId, startedAt, "FAILURE", 1, 0);
            return false;
        }

        try {
            embeddingRepository.upsertVersioned(
                    assetId,
                    MediaAssetEmbeddingType.IMAGE.dbValue(),
                    embeddingJson,
                    model,
                    sourceHash,
                    0L,
                    processingVersion);
            record(assetId, startedAt, "SUCCESS", 1, 0);
            return true;
        } catch (Exception error) {
            log.warn("Failed to store image embedding for asset {}: {}", assetId, error.getMessage());
            record(assetId, startedAt, "FAILURE", 1, 0);
            return false;
        }
    }

    private static String sha256(String value) {
        try {
            return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256")
                    .digest(value.getBytes(StandardCharsets.UTF_8)));
        } catch (Exception error) {
            throw new IllegalStateException("Could not hash image embedding source", error);
        }
    }

    private void record(UUID assetId, long startedAt, String outcome,
            int providerCalls, int duplicateCallsAvoided) {
        if (mediaAiTelemetry != null) {
            mediaAiTelemetry.record("VOYAGE_IMAGE_EMBEDDING",
                    MediaAiTelemetryService.elapsedMillis(startedAt), outcome,
                    assetId, null, 1, providerCalls, duplicateCallsAvoided);
        }
    }
}
